### ISSUE TITLE
Create dropdown with actions on header user avatar

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#108] opened 2023-08-31 06:29 UTC
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/85d1127b-dbab-403e-9fc6-3c497d2ce5ee)

- [ ] Remove Profile link from Header avatar

**User story:**
As a logged-in user, I want to see a “Profile” link and the “Logout” button  in the dropdown menu, So that I can easily navigate to my profile page to view and manage my profile information or quickly log out from the application when I want to end my session.

**Acceptance criteria:**
- [ ] Clicking on the header avatar should open a dropdown menu.
- [ ] When the dropdown menu is open, there should be a “Logout” button and a “Profile” link visible.
- [ ] Clicking the “Profile” link the user is redirected to their profile page.
- [ ] The dropdown menu should be closed after redirection.
- [ ] Clicking the “Logout” button should log the user out of the application.
- [ ] After clicking the “Logout” button, the user should be redirected to the Sign In page.

**Comment by Neyrinka** [comment] 2023-09-07 14:06
**Summary:**	The Dropdown in the Header is displayed in the upper right corner, not tied to the avatar when the screen width is less than 847 px.

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Expected Result:**	The Dropdown in the Header is displayed below the Avatar after clicking the Avatar icon.

**Attachments:**	

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/328ddfae-b35c-424f-b7d5-da5e8ca5c8fb)


**Severity:**	Low
**Priority:**	Medium


- [ ] Remove the "X" icon from the Dropdown.


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/ea02112e-b713-4358-af61-e40615175eb7)

**Comment by kovAnya** [comment] 2023-09-14 06:37
the crossmark was removed. The positioning of dropdown was caused by the other component and is fixed now (besides the user profile - it will be ok there, when the author component will be customized for mobile and tablet screens (215 ticket))

**Closed as completed** 2023-09-14 09:37 UTC
Labels: wr-v1, bug
