### ISSUE TITLE
Add responsive for Sign In/Up pages

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#139] opened 2023-09-04 07:55 UTC
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/2400e975-7735-4fef-a8b0-0a4435ffd947)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/b0ffbb9e-8a82-4e83-a6e2-dde9ec4b0082)

- [x] Add responsiveness for Auth pages (right side with bg should hide on narrow screens)
- [x] Check out bg images covering placement (as of now bg images are moving out on wide screens)

**Comment by lera777** [comment] 2023-09-07 01:16
**Description**
The text within the "Sign in with Google" button wraps to a new line and falls outside the button's boundaries, when using a screen resolution of 775 x 600 px.


**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2 Reduce the screen resolution to 775 x 600 pixels.
3 Pay attention to the text within the "Sign in with Google" button wraps to a new line and falls outside the button's boundaries.

**Actual result:** 
The text within the "Sign in with Google" button wraps to a new line and falls outside the button's boundaries, when using a screen resolution of 775 x 600 px.

**Expected result:** 
The "Sign in with Google" button should adapt to the screen size and display the text correctly without any overflow or wrapping issues.

**Additional information:**
There is also an issue with adapting to the screen size in the next screenshot.



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/72eea79c-73ac-48fb-9378-e5860da612d9)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/0606ca0d-cbac-40af-a535-d09e6e697069)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/cbe78b61-b8ba-40b6-836c-0b6a23a5c596)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/a68bc723-d300-47ab-b2f6-034e2de37045)


**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Medium

**Priority:**
Medium

**Comment by AnastasiaR2** [comment] 2023-09-07 04:52
As the logo task is merged, the issue is resolved now. 


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/85576361/8972ff9c-d784-4d86-a426-aa37dcdee0fd)

**Closed as completed** 2023-09-13 23:26 UTC
Labels: bug, wr-v2
